<form method="POST" action="{{ url_for('user', { 'id': user.id }) }}">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div><label for="user[name]">Name:</label><input type="text" name="user[name]" value="{{ user.name|striptags }}"></div>
    {% if errors['name'] is not empty %}
    <div>{{errors['name']}}</div>
    {% endif %}
    <div><label for="user[lastname]">Last Name:</label><input type="text" name="user[lastname]" value="{{ user.lastname|striptags }}"></div>
    {% if errors['lastname'] is not empty %}
    <div>{{errors['lastname']}}</div>
    {% endif %}
    <div><label for="user[email]">Email:</label><input type="text" name="user[email]" value="{{ user.email|striptags }}"></div>
    {% if errors['email'] is not empty %}
    <div>{{errors['email']}}</div>
    {% endif %}
    <input type="submit" value="Ubdate">
</form>