{% block body %}

<form action="">
    <input type="text" name="term" value="{{ term|striptags }}">
    <input type="submit" value="Find user">
</form>
<a href="{{url_for('adduser')}}">Регистрация</a>, <a href="{{url_for('auth')}}">Авторизация</a>
<p>{{ message }}</p>
<ul>
    {% for user in users %}
        <li>
            <a href="{{ url_for('user', { 'id': (user.id) }) }}">{{ user.name }}</a>
            {% if user.lastname is not empty %}
                - {{ user.lastname }}
            {% endif %}
            - {{ user.email}}
            : <a href="{{ url_for('edituser', { 'id': (user.id) }) }}">edit</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}